---
title: "Project"
author: "William Dunne"
date: "19 September 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(keras)
```

```{r}
data <- read.csv("P3S2_hourly_clean.csv")


IDs <- unique(data[,1])


id2 <- data.frame(length(IDs))
for (i in IDs){
  id2[i,] = data %>%
  filter(respondent_id == i) %>%
  select(starts_with("hour"), "plan_date", "respondent_id") %>%
  gather(value = hour, key = plan_date) 
}



#data2 <- cbind(n_data_101, total = rowSums(data2)) %>%
 # select(total)


#acf(diff(as.numeric(n_data_101), lag.max = 14, type = 'correlation')

```

There are 24 unique ID's and 17 unique timezones, with 3 named oddly... doing an ACF test to lag 14 shows that all respondent had autocorrelation occuring by day.

```{r}
n_1 <- round(nrow(n_data_101) * .70, digits = 0)
n_2 <- round(nrow(n_data_101) * .90, digits = 0)
train <- n_data_101[1:n_1,]
val <- n_data_101[{n_1+1}:n_2,]
test <- n_data_101[{n_2+1}:{nrow(n_data_101)},]




model <- keras_model_sequential() %>% 
  layer_dense(units = 32, input_shape = c(784), activation = "relu") %>% 
  layer_dense(units = 1)

model %>% compile(
  optimizer = optimizer_rmsprop(),
  loss = "mae"
)

history <- model %>% fit_generator(
  train,
  steps_per_epoch = 500,
  epochs = 30,
  validation_data = val,
  validation_steps = 100
)


```

